export const blueLvl = [
  ['szczery do bólu', ['outspoken', 'brutally honest']],
  ['sumienny', ['conscientious', 'scrupulous']],
  ['chropowaty', ['rough', 'rugged', 'scabrous']],
  ['niemodnie', ['dowdy', 'unfashionable', 'outdated']],
  ['wabić', ['lure', 'allure']],
  ['przysięga', ['pledge', 'oath', 'vow']],
  ['odbywać próby', ['rehearse']],
  ['paproć', ['fern']],
  [
    'rozwodzić się nad czymś',
    ['dwell', 'expatiate', 'dwell on something', 'dwell on'],
  ],
  ['erudyta', ['scholar', 'erudite']],
  ['warczeć', ['growl', 'snarl']],
  ['skowronek', ['lark']],
  ['wzdymać', ['bloat', 'gasp']],
  ['maczuga', ['club', 'mace']],
  ['wzbogacać', ['enrich', 'enrich with something', 'enrich with']],
  ['rozpuszczalnik', ['solvent']],
  ['oburzać się', ['outrage', 'resent', 'revolt']],
  ['podwozie', ['chassis']],
  ['ulec', ['succumb', 'give in', 'succumb to']],
  ['łom', ['crowbar']],
];
