export const blueLvl = [
  ['szczery do bólu', ['brutally honest']],
  ['sumienny', ['conscientious', 'scrupulous']],
  ['chropowaty', ['rugged', 'scabrous']],
  ['niemodnie', ['unfashionable']],
  ['wabić', ['lure']],
  ['przysięga', ['pledge']],
  ['odbywać próby', ['rehearse']],
  ['paproć', ['fern']],
  ['rozwodzić się nad czymś', ['dwell', 'expatiate']],
  ['erudyta', ['erudite']],
  ['warczeć', ['growl', 'snarl']],
  ['skowronek', ['lark']],
  ['wzdymać', ['gasp']],
  ['maczuga', ['club']],
  ['wzbogacać', ['enrich']],
  ['rozpuszczalnik', ['solvent']],
  ['oburzać się', ['resent', 'revolt']],
  ['podwozie', ['chassis']],
  ['ulec', ['succumb', 'give in']],
  ['łom', ['crowbar']],
];
