export const greenLvl = [
  ['kamienica', ['tenement', 'tenement house']],
  ['zwinny', ['agile', 'dexterous']],
  [
    'popierać kogoś',
    [
      'back',
      'back somebody up',
      'support',
      'to back somebody',
      'to support somebody',
    ],
  ],
  ['podkoszulek', ['undershirt', 'singlet']],
  ['znaczący, ważny', ['significant', 'important']],
  ['montować', ['install', 'assemble', 'mount']],
  ['cecha', ['trait'], 'feature', 'characteristic'],
  ['niewystarczający', ['insufficient']],
  ['aportować', ['fetch']],
  ['trawnik', ['lawn', 'grass']],
  ['podmiejski', ['suburban']],
  ['zniechęcać', ['discourage']],
  ['urządzenie domowe', ['home appliance']],
  ['czujny', ['alert']],
  ['zgłaszać, meldować', ['report']],
  ['deska', ['board', 'plank']],
  ['krzywy', ['crooked', 'warped', 'skewed', 'curvy']],
  ['pochwalić', ['praise', 'commend']],
  ['gęstość', ['density', 'thickness']],
  ['odrzucać (ofertę)', ['reject', 'turn down']],
  ['bocian', ['stork']],
  ['pielęgnować', ['nurture', 'take care', 'nurse']],
  ['kołyska', ['crib', 'cradle']],
  ['wyróżniać się', ['stand out', 'distinguish oneself']],
  ['obojczyk', ['collarbone', 'collar bone', 'clavicle']],
];
