export const orangeLvl = [
  ['naprawić, zamocować', ['fix', 'repair', 'fix up']],
  ['ręcznik', ['towel']],
  ['rzadki', ['rare']],
  ['pójść za kimś, śledzić', ['follow']],
  ['przyczyna', ['reason', 'cause']],
  [
    'paskudny, wstrętny',
    ['nasty', 'hideous', 'awful', 'terrible', 'disgusting'],
  ],
  ['wpaść do kogoś', ['drop in', 'drop by', 'come over']],
  ['ilość', ['quantity', 'amount']],
  ['pewien (określony)', ['certain']],
  ['doręczać', ['deliver']],
  ['gołąb', ['pidgeon']],
  ['nowoczesny', ['modern']],
  ['stosować', ['apply', 'use']],
  ['mąka', ['flour']],
  ['prosto', ['straight']],
  [
    'przepraszać za coś',
    [
      'apologize',
      'apologise',
      'apologise for something',
      'apologize for something',
    ],
  ],
  ['gniazdko elektryczne', ['electric socket', 'socket']],
  ['zwykły', ['ordinary', 'normal', 'usual', 'typical']],
  ['chrapać', ['snore']],
  ['port', ['harbor', 'harbour', 'port']],
  ['roztopiony', ['melted']],
  ['rozejrzeć się', ['look around']],
  ['grubość', ['thickness']],
  ['dogodny', ['convenient', 'suitable']],
  [
    'rozwiązać problem',
    ['solve a problem', 'solve', 'take care', 'take care of a problem'],
  ],
];
