export const yellowLvl = [
  ['myśleć', ['think', 'to think']],
  ['ludzie', ['people']],
  ['dobry', ['good']],
  ['potrzebować', ['need']],
  ['biżuteria', ['jewelry', 'jewellery']],
  ['biedny', ['poor']],
  ['rozmawiać', ['talk', 'speak']],
  ['sok', ['juice']],
  [
    'wspaniały',
    ['great', 'magnificent', 'wonderful', 'amazing', 'awesome', 'fantastic'],
  ],
  ['zostać', ['stay']],
  ['ubrania', ['clothes']],
  ['miękki', ['soft']],
  ['jechać autem', ['drive a car', 'drive']],
  ['fotel', ['armchair']],
  ['sprytny, bystry', ['clever', 'smart']],
  ['zgadzać się', ['agree']],
  ['miska', ['bowl']],
  ['cichy', ['quiet', 'silent']],
  ['ściągać (ubranie)', ['take off']],
  ['lek', ['medicine', 'drug']],
  ['podobny', ['similar']],
  ['zgadywać', ['guess']],
  ['szyja', ['neck']],
  ['powoli', ['slowly']],
  ['znaczyć coś', ['mean', 'mean something']],
  ['chodnik', ['pavement', 'sidewalk']],
  ['wąski', ['narrow']],
  ['nosić (ciuchy)', ['wear', 'wear clothes']],
  ['koc', ['blanket']],
  ['gorzki', ['bitter']],
];
